apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleservice-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: ui
  template:
    metadata:
      labels:
        bb: ui
    spec:
      containers:
      - name: ui-site
        image: exampleservice-ui:0.0.1-SNAPSHOT
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka-cm
              key: eureka_service_address
        - name: ENVIRONMENT
          value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: ui
  ports:
  - port: 9091
    targetPort: 9091
    nodePort: 30091