server:
  port: 9090
spring:
  application:
    name: book-ui-service
    
# Configuration for database
  jpa:
    hibernate:
      ddl-auto: none 
      
    # Auto generate the schema  
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: target/resources-gen/sql/schema.sql

# Configuration for service discovery server
eureka:
  instance:
    # Leave prefer ip address to allow the gateway inside the kubernetes cluster to find this service by it's pod ip
    preferIpAddress: true
    # The hostname of the service, to register the pod and turn it easier for the gateway to find it
    hostname: book-ui-service
  client:
    registerWithEureka: true
    fetchRegistry: true    
    service-url:
      defaultZone: http://10.100.100.101:8761/eureka
      
logging:
  file:
    path: target/logs
    name: ${logging.file.path}/GatewayService.log  
    

# Customer properties used in the service
security:
  jwt:
    token:
      secret-key: secretKeyVerLonggggggggggggggggggggg
      expiration: 600000